# Generated by Django 5.2.6 on 2025-10-06 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='days',
            old_name='operationsIn',
            new_name='operationsR',
        ),
        migrations.RenameField(
            model_name='days',
            old_name='operationsOut',
            new_name='operationsV',
        ),
        migrations.AddField(
            model_name='transactions',
            name='after',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='transactions',
            name='before',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='days',
            name='Balance',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='days',
            name='initBalance',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='type',
            field=models.CharField(choices=[('versement', 'Versement'), ('retrait', 'Retrait')], max_length=10),
        ),
    ]
