# Generated by Django 5.2.6 on 2025-10-06 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_rename_operationsin_days_operationsr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='days',
            name='benefit',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='after',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='before',
            field=models.FloatField(default=0),
        ),
    ]
