# Generated by Django 5.2.6 on 2025-10-06 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_days_benefit_alter_transactions_after_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='type',
            field=models.CharField(choices=[('versement', 'Versement'), ('retrait', 'Retrait'), ('augmante', 'Augmante')], max_length=10),
        ),
    ]
