# Generated by Django 5.2.6 on 2025-10-06 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_transactions_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='phone',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
