# Generated by Django 5.2.6 on 2025-10-07 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_transactions_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='type',
            field=models.CharField(choices=[('versement', 'Versement'), ('retrait', 'Retrait'), ('augmante', 'Augmante'), ('check', 'Check')], max_length=10),
        ),
    ]
