# Generated by Django 5.2.6 on 2025-10-07 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_transactions_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='descriptions',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
