# Generated by Django 5.2.6 on 2025-10-08 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_transactions_descriptions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='comission',
            field=models.FloatField(default=0),
        ),
    ]
