# Generated by Django 5.2.6 on 2025-10-08 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_transactions_comission'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='isCanceled',
            field=models.BooleanField(default=False),
        ),
    ]
