# Generated by Django 5.2.6 on 2025-10-08 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_transactions_iscanceled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='type',
            field=models.CharField(choices=[('versement', 'Versement'), ('retrait', 'Retrait'), ('retraitMostevid', 'RetraitMostevid'), ('augmante', 'Augmante'), ('check', 'Check')], max_length=16),
        ),
    ]
