# Generated by Django 5.2.6 on 2025-10-08 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_alter_transactions_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='days',
            name='cash',
            field=models.FloatField(default=0),
        ),
    ]
