# Generated by Django 5.2.6 on 2025-10-08 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_days_cash'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='cashAfter',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='transactions',
            name='cashBefore',
            field=models.FloatField(default=0),
        ),
    ]
