# Generated by Django 5.2.6 on 2025-10-10 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_transactions_cashafter_transactions_cashbefore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='type',
            field=models.CharField(choices=[('versement', 'Versement'), ('retrait', 'Retrait'), ('retrait_coms', 'Retrait_coms'), ('retraitMostevid', 'RetraitMostevid'), ('augmante', 'Augmante'), ('check', 'Check'), ('manualeVersement', 'ManualeVersement'), ('manualeRetrait', 'ManualeRetrait')], max_length=16),
        ),
    ]
