# Generated by Django 5.2.6 on 2025-10-10 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_agency'),
    ]

    operations = [
        migrations.AddField(
            model_name='days',
            name='agency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='store.agency'),
            preserve_default=False,
        ),
    ]
