# Generated by Django 5.2.6 on 2025-10-10 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_days_agency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='days',
            name='agency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agency', to='store.agency'),
        ),
    ]
