# Generated by Django 5.2.6 on 2025-10-10 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_alter_days_agency'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='agency',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
