# Generated by Django 5.2.6 on 2025-10-10 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_users_agency'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='Agency',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
