# Generated by Django 5.2.6 on 2025-10-10 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_transactions_agency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactions',
            name='Agency',
        ),
        migrations.AlterField(
            model_name='agency',
            name='name',
            field=models.CharField(max_length=250, unique=True),
        ),
        migrations.AddField(
            model_name='transactions',
            name='agency',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
