# Generated by Django 5.2.6 on 2025-10-11 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_alter_agency_name_alter_days_agency'),
    ]

    operations = [
        migrations.CreateModel(
            name='LastTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('type', models.CharField(max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.days')),
            ],
            options={
                'indexes': [models.Index(fields=['phone', 'type', 'day'], name='store_lastt_phone_8a0c62_idx')],
            },
        ),
    ]
