# Generated by Django 5.2.6 on 2025-10-11 16:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_lasttransaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lasttransaction',
            name='created_at',
        ),
        migrations.AddField(
            model_name='lasttransaction',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
