# Generated by Django 5.2.6 on 2025-10-13 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_remove_lasttransaction_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lasttransaction',
            name='amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='phones',
            name='phone',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='amount',
            field=models.FloatField(),
        ),
    ]
