# Generated by Django 5.2.6 on 2025-10-20 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0024_alter_lasttransaction_amount_alter_phones_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='days',
            name='agency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agency', to='store.agency'),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='agency',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
