# Generated by Django 5.2.6 on 2025-11-04 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0025_alter_days_agency_alter_transactions_agency'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='expireDate',
            field=models.DateField(default='2026-10-08'),
            preserve_default=False,
        ),
    ]
